services:
  fastapi-service:
    restart: on-failure
    container_name: fastapi-service
    hostname: fastapi-service
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      - RPC_HOST=grpc-service
    volumes:
      - .:/app
    ports:
      - 5001:8888
    depends_on:
      - grpc-service
    networks:
      - grpc-network
  grpc-service:
    restart: always
    container_name: grpc-service
    hostname: grpc-service
    build:
      context: .
      dockerfile: ./service/Dockerfile
    volumes:
      - .:/app
    ports:
      - 50051:50051
    environment:
      - DB_HOST=db
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - grpc-network
  db:
    image: postgres
    restart: on-failure
    container_name: grpc-db
    hostname: grpc-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:?err}:5432
    environment:
      - POSTGRES_DB=${DB_NAME:?err}
      - POSTGRES_USER=${DB_USER:?err}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?err}
      - POSTGRES_PORT=${DB_PORT:?err}
    networks:
      - grpc-network
volumes:
  pgdata:

networks:
  grpc-network: