"""add union field to notes table

Revision ID: c25afbbe7fdc
Revises: 7a886bd730fa
Create Date: 2025-09-14 15:15:09.744903

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c25afbbe7fdc"
down_revision: Union[str, Sequence[str], None] = "7a886bd730fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_notes_user_id"), "notes", ["user_id"], unique=False)
    op.create_foreign_key(
        None,
        "notes",
        "users",
        ["user_id"],
        ["uuididf"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "notes", type_="foreignkey")
    op.drop_index(op.f("ix_notes_user_id"), table_name="notes")
    op.drop_column("notes", "user_id")
    # ### end Alembic commands ###
