# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service.protos.notes_pb2 as notes__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in notes_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class NoteServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create = channel.unary_unary(
            "/notes_app.NoteService/create",
            request_serializer=notes__pb2.GRPCCreateNoteMessage.SerializeToString,
            response_deserializer=notes__pb2.GRPCNoteMessage.FromString,
            _registered_method=True,
        )
        self.get = channel.unary_unary(
            "/notes_app.NoteService/get",
            request_serializer=notes__pb2.GRPCGetNoteMessage.SerializeToString,
            response_deserializer=notes__pb2.GRPCNoteMessage.FromString,
            _registered_method=True,
        )
        self.update = channel.unary_unary(
            "/notes_app.NoteService/update",
            request_serializer=notes__pb2.GRPCUpdateNoteMessage.SerializeToString,
            response_deserializer=notes__pb2.GRPCNoteMessage.FromString,
            _registered_method=True,
        )
        self.list = channel.unary_unary(
            "/notes_app.NoteService/list",
            request_serializer=notes__pb2.GRPCGetListNoteMessage.SerializeToString,
            response_deserializer=notes__pb2.GRPCNoteListMessage.FromString,
            _registered_method=True,
        )
        self.delete = channel.unary_unary(
            "/notes_app.NoteService/delete",
            request_serializer=notes__pb2.GRPCDeleteNoteMessage.SerializeToString,
            response_deserializer=notes__pb2.GRPCDeleteNoteMessage.FromString,
            _registered_method=True,
        )


class NoteServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_NoteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "create": grpc.unary_unary_rpc_method_handler(
            servicer.create,
            request_deserializer=notes__pb2.GRPCCreateNoteMessage.FromString,
            response_serializer=notes__pb2.GRPCNoteMessage.SerializeToString,
        ),
        "get": grpc.unary_unary_rpc_method_handler(
            servicer.get,
            request_deserializer=notes__pb2.GRPCGetNoteMessage.FromString,
            response_serializer=notes__pb2.GRPCNoteMessage.SerializeToString,
        ),
        "update": grpc.unary_unary_rpc_method_handler(
            servicer.update,
            request_deserializer=notes__pb2.GRPCUpdateNoteMessage.FromString,
            response_serializer=notes__pb2.GRPCNoteMessage.SerializeToString,
        ),
        "list": grpc.unary_unary_rpc_method_handler(
            servicer.list,
            request_deserializer=notes__pb2.GRPCGetListNoteMessage.FromString,
            response_serializer=notes__pb2.GRPCNoteListMessage.SerializeToString,
        ),
        "delete": grpc.unary_unary_rpc_method_handler(
            servicer.delete,
            request_deserializer=notes__pb2.GRPCDeleteNoteMessage.FromString,
            response_serializer=notes__pb2.GRPCDeleteNoteMessage.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "notes_app.NoteService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("notes_app.NoteService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class NoteService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/notes_app.NoteService/create",
            notes__pb2.GRPCCreateNoteMessage.SerializeToString,
            notes__pb2.GRPCNoteMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def get(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/notes_app.NoteService/get",
            notes__pb2.GRPCGetNoteMessage.SerializeToString,
            notes__pb2.GRPCNoteMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def update(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/notes_app.NoteService/update",
            notes__pb2.GRPCUpdateNoteMessage.SerializeToString,
            notes__pb2.GRPCNoteMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def list(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/notes_app.NoteService/list",
            notes__pb2.GRPCGetListNoteMessage.SerializeToString,
            notes__pb2.GRPCNoteListMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/notes_app.NoteService/delete",
            notes__pb2.GRPCDeleteNoteMessage.SerializeToString,
            notes__pb2.GRPCDeleteNoteMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
