syntax = "proto3";

package notes_app;

message GRPCNoteMessage{
    string uuididf = 1;
    string userUuididf = 2;
    string name = 3;
    string message = 4;
}       
message GRPCCreateNoteMessage{
    string uuididf = 1;
    string name = 2;
    string message = 3;
    string userUuididf = 4;

}
message GRPCUpdateNoteMessage{
    string uuididf = 1;
    string name = 2;
    string message = 3;
}
message GRPCDeleteNoteMessage{
    string uuididf = 1;
}
message GRPCGetNoteMessage{
    string uuididf = 1;
}
message GRPCGetListNoteMessage{
    string userUuididf = 1;
}
message GRPCNoteListMessage{
    repeated GRPCNoteMessage notes = 1;
}

service NoteService{
    rpc create(GRPCCreateNoteMessage) returns (GRPCNoteMessage);
    rpc get(GRPCGetNoteMessage) returns (GRPCNoteMessage);
    rpc update(GRPCUpdateNoteMessage) returns (GRPCNoteMessage);
    rpc list(GRPCGetListNoteMessage) returns (GRPCNoteListMessage);
    rpc delete(GRPCDeleteNoteMessage) returns (GRPCDeleteNoteMessage);
}